INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Push-ups", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Squats", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Pull-ups", "BK", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lunges", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bench press", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plank", "AB", True, 3);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bicep curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Tricep dips", "AR", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Leg press", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Shoulder press", "SH", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Crunches", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Russian twists", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Calf raises", "LG", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bicycle crunches", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Mountain climbers", "CR", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Side plank", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hamstring curls", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping jacks", "CR", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Skull crushers", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Deadlifts", "BK", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Step-ups", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Incline bench press", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Russian twists with medicine ball", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bent-over rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Wall sits", "LG", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Flutter kicks", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jump rope", "CR", True, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Arnold press", "SH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Leg extensions", "LG", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Incline dumbbell curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Skull crushers with EZ bar", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lat pulldowns", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Romanian deadlifts", "BK", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Russian twists with kettlebell", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Side lunges", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("High knees", "CR", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lateral raises", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Leg curls", "LG", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hammer curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Close-grip bench press", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Stability ball crunches", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Seated cable rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Standing calf raises", "LG", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Burpees", "CR", True, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Military press", "SH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Squat jumps", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Concentration curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Tricep kickbacks", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Glute bridges", "LG", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Ab wheel rollouts", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("T-bar rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Reverse lunges", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jump squats", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Push-up variations", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Front raises", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Step-ups with weights", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Preacher curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Diamond push-ups", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("V-ups", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bent-over flyes", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Romanian deadlifts with dumbbells", "BK", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Box jumps", "LG", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Tricep pushdowns", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Leg raises", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Running", "CR", False, 12);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cycling", "CR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Swimming", "CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping rope", "CR", True, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Walking", "CR", False, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Treadmill running", "CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Elliptical training", "CR", False, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Stair climbing", "CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("High-intensity interval training", "CR", True, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plank jacks", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell bench press", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bent-over reverse flyes", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Leg press machine", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Push-up and row", "CH", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell swings", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hammer curls with dumbbells", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable flyes", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Reverse crunches", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lat pulldown machine", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Box squats", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lateral shoulder raises", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Side plank dips", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Good mornings", "BK", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bicycle crunches with weights", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Wall push-ups", "CH", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Leg press calf raises", "LG", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Standing overhead press", "SH", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Decline push-ups", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sumo squats", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Renegade rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Split squats", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dips", "AR", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Russian twists with stability ball", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Wide-grip pull-ups", "BK", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Barbell hip thrusts", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hammer curls with cable", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hack squats", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hanging leg raises", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric push-ups", "CH", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Single-leg deadlifts", "BK", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Seated dumbbell shoulder press", "SH", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Weighted sit-ups", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Standing barbell curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Close-grip pull-downs", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Side lunges with dumbbells", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Russian twists on stability ball", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Reverse grip barbell curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell pullovers", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Reverse flyes with bands", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Skater lunges", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Medicine ball slams", "CR", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plate front raises", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Weighted step-ups", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Spiderman planks", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Burpee box jumps", "CR", True, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Incline dumbbell flyes", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bent-over dumbbell rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Barbell lunges", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell shoulder raises", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Medicine ball twists", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable kickbacks", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sumo deadlifts", "BK", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Reverse crunches on bench", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Single-arm cable rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping rope with double unders", "CR", True, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Boxing punches", "AR", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sissy squats", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell hammer curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Standing cable chest press", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Side plank leg lifts", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bulgarian split squats", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Medicine ball burpees", "CR", True, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lateral shoulder raises with dumbbells", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Weighted Russian twists", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Donkey calf raises", "LG", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Seated military press", "SH", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Single-leg calf raises", "LG", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Barbell bench press", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Russian twist with resistance band", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Machine rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jump squats with weight", "AR", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Seated leg press", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Resistance band curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lateral lunges", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Mountain climbers on sliders", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell incline bench press", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plate twists", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable lat pull-downs", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Curtsy lunges", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Medicine ball chest pass", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Zottman curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Roman chair leg raises", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping jacks with resistance band", "CR", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable bicep curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hack squats with dumbbells", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Single-arm dumbbell shoulder press", "SH", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Resistance band pull-aparts", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Weighted Russian twists on bench", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell pullover on stability ball", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Scissor kicks", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Medicine ball woodchoppers", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plate front raises with rotation", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable tricep push-downs", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Single-leg glute bridges", "LG", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell renegade rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Incline push-ups", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Banded squats", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell hammer curls with twist", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Resistance band pull-throughs", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable crunches", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with dumbbells", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Barbell curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Standing cable flyes", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell goblet squats", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Roman chair back extensions", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable upright rows", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bosu ball Russian twists", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell kickbacks", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Seated calf raises", "LG", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Incline dumbbell curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bench dips", "AR", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Overhead tricep extensions", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Decline sit-ups", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Pike push-ups", "SH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Resistance band squats", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Goblet squats with kettlebell", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Standing calf raises with dumbbells", "LG", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lying leg curls", "LG", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hamstring curls with stability ball", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Incline cable flyes", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell shrugs", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lateral lunges with dumbbells", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Burpee pull-ups", "BK", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plank with leg lifts", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lying tricep extensions", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Seated leg extensions", "LG", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable woodchoppers", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Concentration curls with dumbbell", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Reverse grip lat pull-downs", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Glute-ham raises", "BK", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable oblique crunches", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Reverse lunges with dumbbells", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Box jumps with dumbbells", "LG", True, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Push-up variations on medicine ball", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Reverse grip dumbbell bench press", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plank with knee tucks", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lying cable curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Single-arm dumbbell rows", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Seated leg curls", "LG", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable lateral raises", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Standing barbell calf raises", "LG", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with weight", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bosu ball plank", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Incline push-ups on stability ball", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell sumo squats", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Behind-the-neck lat pull-downs", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Medicine ball push-ups", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Overhead press with dumbbells", "SH", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable rope crunches", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell alternating curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bent-over cable lateral raises", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Bulgarian split squats with dumbbells", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable tricep extensions", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell swings with one arm", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Resistance band face pulls", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Incline dumbbell flyes on stability ball", "CH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell bent-over rear delt raises", "SH", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Single-leg press", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable hammer curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Seated dumbbell curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell step-ups", "LG", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Single-leg Romanian deadlifts", "BK", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable crunches with rotation", "AB", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plate curls", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Single-leg calf raises with dumbbell", "LG", True, 4);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Front squats", "LG", True, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plate twists on stability ball", "AB", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable lat push-downs", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Walking lunges", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell clean and press", "SH", True, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cable woodchoppers with rotation", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Lying tricep cable extensions", "AR", True, 5);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Dumbbell lunges", "LG", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Standing cable reverse flyes", "BK", True, 6);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Mountain climbers", "CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Burpees", "CR", False, 12);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping jacks", "CR", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint intervals", "CR", False, 14);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Mountain bike riding", "CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Rowing", "CR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hiking", "CR", False, 7);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cross-country skiing", "CR", False, 12);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Battle ropes", "AR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Deadlifts", " BK", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Boxing", " AR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("High knees", " LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sledgehammer swings", " AR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping rope variations", " CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Swimming laps", " CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell snatches", " LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric lunges", " LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint cycling", " CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sled pushes", " LG", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Battling ropes", " AR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Circuit training", " Various", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint intervals on a treadmill", " CR", False, 12);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Mountain climbers with sliders", " CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Box jumps variations", " LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("High-intensity interval training (HIIT)", " Various", False, 12);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint swimming", " CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Rowing machine intervals", " CR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hill sprints", " LG", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Medicine ball slams", " Various", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kickboxing", " AR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jump squats", " LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Circuit weight training", " Various", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Obstacle course training", " Various", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Interval running", " CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint training", " Various", False, 12);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric push-ups", " CH", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("TRX exercises", " Various", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sandbag training", " Various", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Rock climbing", " Various", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jump lunges", " LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint cycling on a stationary bike", " CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric box drills", " LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Aerobic dance workouts", " Various", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint rowing", " CR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Tire flips", " LG", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Explosive jumps", " Various", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Stair sprints", " LG", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint intervals on an elliptical machine", " CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Tabata workouts", " Various", False, 12);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint intervals on a stationary bike", " CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Slam ball variations", " Various", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Tire drag", " LG", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Interval swimming", " CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with weight", " LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Boxing combinations", "AR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping rope double unders", "CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell swings", "AR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with rotation", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Rock climbing (indoor or outdoor)", "BK", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Medicine ball slams", "AR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric box jumps", "LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint intervals on a stationary bike", "CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Tire flips", "LG", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Battle rope waves", "AR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Rowing machine sprints", "CR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("HIIT workouts (High-Intensity Interval Training)", "Various", False, 12);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Boxing pad work", "AR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Skiing or snowboarding", "BK", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Explosive push-ups", "CH", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping squats with weight", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Barbell thrusters", "LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell clean and press", "SH", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Cycling sprints", "CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint intervals on a treadmill", "CR", False, 12);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric burpees", "Various", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with dumbbells", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Agility ladder drills", "Various", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint swimming", "CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric push-ups with clap", "CH", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Battle rope slams", "AR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("High knees with resistance bands", "CR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint rowing", "CR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Treadmill hill sprints", "LG", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Box jumps with height variations", "LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell snatches", "LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with kettlebell", " LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric step-ups", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Boxing speed bag training", "AR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint cycling on a stationary bike", "CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell Turkish get-ups", "Various", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with medicine ball", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric lateral jumps", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Parkour movements", "Various", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint intervals on an elliptical machine", "CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Battling rope alternating waves", "AR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell snatches with one arm", "LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Explosive box squats", "LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric push-ups on medicine ball", "CH", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with resistance bands", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint intervals on a rowing machine", "CR", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell windmills", "LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric lateral lunges", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Aggressive rope slams", "AR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint cycling with resistance", "CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with sandbag", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric push-ups with medicine ball", "CH", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint intervals on a stair climber", "CR", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Kettlebell figure 8s", "LG", False, 9);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Plyometric single-leg hops", "LG", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Hill sprints with weight", "LG", False, 10);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Agility ladder lateral drills", "Various", False, 8);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Sprint swimming with resistance", "CR", False, 11);
INSERT INTO gym_exercise (name, body_part, is_repetitive, calories_burned) VALUES ("Jumping lunges with kettlebell swing", "LG", False, 8);
