INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Apple", "F", 52, 14.0, 0.2, 0.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Banana", "F", 105, 27.0, 0.4, 1.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Breast", "F", 165, 0.0, 3.6, 31.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Salmon", "F", 206, 0.0, 13.0, 22.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Broccoli", "F", 55, 11.0, 0.6, 3.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Brown Rice (Cooked)", "F", 111, 23.0, 0.9, 2.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Whole Wheat Bread", "F", 247, 49.0, 2.7, 10.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Eggs (Large)", "F", 155, 1.1, 10.6, 12.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Greek Yogurt", "F", 59, 3.6, 0.0, 10.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Almonds", "F", 576, 22.0, 49.0, 21.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Olive Oil", "F", 884, 0.0, 100.0, 0.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Milk (2% Fat)", "F", 50, 4.8, 1.8, 3.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Spinach", "F", 23, 3.6, 0.4, 2.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Carrot", "F", 41, 10.0, 0.2, 0.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Lean Ground Beef (Cooked)", "F", 250, 0.0, 17.0, 23.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Oatmeal (Cooked)", "F", 68, 12.0, 1.4, 2.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Sweet Potato (Baked)", "F", 86, 20.0, 0.1, 1.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cucumber", "F", 15, 3.6, 0.1, 0.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Lentils (Cooked)", "F", 116, 20.0, 0.4, 9.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Peanut Butter (Natural)", "F", 588, 20.0, 50.0, 25.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Orange", "F", 43, 11.0, 0.2, 0.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("White Rice (Cooked)", "F", 130, 28.0, 0.3, 2.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Tuna (Canned in Water)", "F", 116, 0.0, 0.8, 26.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cauliflower", "F", 25, 5.0, 0.3, 2.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pasta (Cooked)", "F", 131, 25.0, 1.3, 5.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Turkey Breast (Skinless)", "F", 104, 0.0, 1.0, 22.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Quinoa (Cooked)", "F", 120, 21.0, 1.9, 4.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cottage Cheese (2% Fat)", "F", 103, 3.4, 2.4, 11.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Strawberries", "F", 32, 8.0, 0.3, 0.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Avocado", "F", 160, 8.5, 14.7, 2.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Ground Beef (80% Lean)", "F", 250, 0.0, 20.0, 18.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Green Beans", "F", 31, 7.0, 0.2, 1.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pineapple", "F", 50, 13.0, 0.1, 0.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Tofu", "F", 144, 1.7, 8.0, 15.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Yogurt", "F", 110, 17.0, 1.5, 7.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Blueberries", "F", 57, 14.0, 0.3, 0.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Walnuts", "F", 654, 14.0, 65.0, 15.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Corn (Cooked)", "F", 96, 21.0, 1.5, 3.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pork Tenderloin", "F", 143, 0.0, 3.5, 26.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Bell Pepper (Red)", "F", 31, 6.0, 0.3, 1.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Mushrooms", "F", 22, 3.3, 0.3, 2.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Peanuts", "F", 567, 16.1, 49.2, 25.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Zucchini", "F", 17, 3.1, 0.3, 1.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Grapes", "F", 69, 18.0, 0.2, 0.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Romaine Lettuce", "F", 17, 3.3, 0.2, 1.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Kidney Beans (Cooked)", "F", 127, 22.8, 0.5, 8.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Parmesan Cheese", "F", 431, 3.4, 29.2, 38.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Honey", "F", 304, 82.0, 0.0, 0.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cantaloupe", "F", 34, 8.0, 0.2, 0.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Green Peas (Cooked)", "F", 81, 14.0, 0.4, 5.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Flaxseeds", "F", 534, 28.9, 42.2, 18.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Raspberries", "F", 53, 12.0, 0.7, 1.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Mango", "F", 60, 15.0, 0.4, 0.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pasta Sauce (Tomato-based)", "F", 56, 9.0, 1.0, 1.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cottage Cheese (Low-Fat)", "F", 72, 3.4, 0.9, 12.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pork Ribs", "F", 272, 0.0, 19.0, 26.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pine Nuts", "F", 673, 13.0, 68.0, 14.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Celery", "F", 16, 3.0, 0.2, 0.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Coconut Milk", "F", 230, 3.3, 24.0, 2.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cottage Cheese (Fat-Free)", "F", 72, 3.4, 0.4, 14.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Grapefruit", "F", 42, 11.0, 0.1, 0.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Hazelnut Butter", "F", 628, 16.7, 61.4, 15.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Maple Syrup", "F", 260, 67.0, 0.0, 0.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Rice Noodles (Cooked)", "F", 96, 23.0, 0.4, 2.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Sesame Seeds", "F", 573, 23.4, 49.0, 17.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Tofu (Firm)", "F", 144, 2.0, 8.0, 15.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Apricot", "F", 48, 12.0, 0.1, 0.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Green Lentils (Cooked)", "F", 116, 20.0, 0.4, 9.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Couscous (Cooked)", "F", 112, 24.0, 0.2, 4.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pecans", "F", 691, 14.0, 72.0, 9.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cottage Cheese (1% Fat)", "F", 72, 3.4, 1.0, 13.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Lamb Chop", "F", 250, 0.0, 20.0, 18.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Sour Cream", "F", 193, 3.6, 20.0, 2.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Kiwi", "F", 41, 9.0, 0.5, 1.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pumpkin", "F", 26, 7.0, 0.1, 1.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Sunflower Seeds", "F", 584, 20.0, 51.0, 21.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cantaloupe Melon", "F", 34, 8.0, 0.2, 0.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Barley (Cooked)", "F", 123, 28.0, 0.4, 2.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cashews", "F", 553, 30.0, 44.0, 18.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Flour (All-Purpose)", "F", 364, 76.3, 1.2, 10.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cherry", "F", 50, 12.0, 0.3, 1.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pasta (Whole Wheat Cooked)", "F", 124, 25.0, 1.1, 5.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Dates", "F", 282, 75.0, 0.4, 2.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("White Bread", "F", 265, 49.7, 2.9, 9.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Mussels (Cooked)", "F", 172, 7.0, 2.9, 24.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pita Bread", "F", 275, 55.0, 2.6, 9.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Peanut Oil", "F", 884, 0.0, 100.0, 0.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Beef Steak", "F", 250, 0.0, 20.0, 23.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pomegranate", "F", 83, 18.7, 1.2, 1.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Naan Bread", "F", 320, 58.0, 5.4, 9.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pork Loin", "F", 143, 0.0, 4.2, 25.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chickpea Flour", "F", 387, 57.8, 6.7, 22.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Custard", "F", 153, 20.0, 6.3, 4.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Salad Dressing (Italian)", "F", 418, 1.6, 45.6, 1.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Hummus", "F", 177, 17.0, 9.0, 6.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pork Sausage", "F", 250, 0.4, 20.0, 16.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pita Chips", "F", 506, 63.0, 26.3, 9.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Tilapia (Cooked)", "F", 96, 0.0, 2.0, 20.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Buttermilk", "F", 62, 4.8, 1.7, 3.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Gouda Cheese", "F", 356, 2.2, 27.8, 24.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pumpkin Seeds", "F", 559, 11.9, 49.0, 30.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Rice Noodles (Dry)", "F", 364, 86.0, 2.2, 6.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Feta Cheese", "F", 264, 4.1, 21.3, 14.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Buckwheat (Cooked)", "F", 92, 19.9, 0.9, 3.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Beef Jerky", "F", 410, 11.3, 15.9, 51.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Soybeans (Cooked)", "F", 173, 9.9, 9.3, 16.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Blue Cheese", "F", 353, 0.7, 28.7, 21.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pork Belly", "F", 525, 0.0, 55.3, 8.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Bulgur (Cooked)", "F", 83, 18.6, 0.2, 3.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Canned Sardines", "F", 208, 0.0, 11.5, 24.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("White Wine", "F", 82, 2.6, 0.0, 0.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Seaweed (Nori)", "F", 35, 5.1, 0.5, 5.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Provolone Cheese", "F", 351, 2.1, 27.7, 25.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pork Sausage Links", "F", 262, 2.0, 22.0, 14.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Bran Flakes", "F", 346, 76.0, 2.7, 9.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Peanut Butter (Crunchy)", "F", 588, 20.0, 50.0, 25.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Coconut Oil", "F", 862, 0.0, 100.0, 0.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Hot Dog", "F", 155, 2.2, 13.0, 5.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Oyster Sauce", "F", 58, 12.9, 0.5, 1.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Red Wine", "F", 85, 2.6, 0.0, 0.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Crab (Cooked)", "F", 83, 0.0, 1.2, 18.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cottage Cheese (Whole Milk)", "F", 103, 3.4, 4.3, 11.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Ginger", "F", 80, 17.8, 0.8, 1.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Breast (Grilled)", "F", 165, 0.0, 3.6, 31.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Salmon Fillet (Grilled)", "F", 206, 0.0, 13.5, 22.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Carrots", "F", 41, 10.0, 0.2, 0.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Grilled Cheese Sandwich", "F", 291, 23.9, 16.9, 11.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Tomato", "F", 18, 3.9, 0.2, 0.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Steak (Grilled)", "F", 250, 0.0, 20.0, 25.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Lettuce", "F", 5, 1.0, 0.1, 0.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Scrambled Eggs", "F", 155, 1.1, 11.0, 13.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Rice (Cooked)", "F", 130, 28.0, 0.3, 2.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Watermelon", "F", 30, 8.0, 0.2, 0.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pizza (Cheese)", "F", 285, 36.2, 10.7, 11.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Grilled Chicken Salad", "F", 120, 2.0, 2.5, 23.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Peanut Butter and Jelly Sandwich", "F", 429, 52.0, 19.0, 12.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Potato", "F", 77, 17.0, 0.1, 2.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cheeseburger", "F", 295, 19.5, 16.4, 16.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Onion", "F", 40, 9.3, 0.1, 1.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Spaghetti (Cooked)", "F", 157, 31.0, 1.5, 5.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Fried Chicken", "F", 319, 12.4, 20.8, 20.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Corn on the Cob", "F", 86, 19.0, 1.2, 3.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Eggs (Hard-Boiled)", "F", 155, 1.1, 11.0, 13.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Strawberry Banana Smoothie", "F", 54, 13.1, 0.4, 0.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Green Beans (Steamed)", "F", 31, 7.0, 0.1, 1.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pancakes (Plain)", "F", 227, 31.3, 9.2, 5.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Water", "F", 0, 0.0, 0.0, 0.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Sushi (Salmon Roll)", "F", 231, 38.0, 6.1, 6.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chocolate Chip Cookie", "F", 488, 64.1, 24.5, 5.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("French Fries", "F", 365, 52.3, 17.5, 3.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Fried Rice", "F", 163, 26.1, 4.5, 4.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Caesar Salad", "F", 200, 3.0, 14.0, 17.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Broccoli Cheddar Soup", "F", 103, 8.4, 6.3, 3.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Peanut Butter", "F", 588, 20.0, 50.0, 25.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Tuna Salad Sandwich", "F", 269, 16.2, 15.1, 18.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Caesar Salad", "F", 154, 2.6, 15.3, 1.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Fried Rice", "F", 222, 28.0, 8.0, 7.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pasta Salad", "F", 157, 17.5, 7.2, 4.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cheese Pizza", "F", 285, 34.0, 11.0, 12.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Grilled Salmon", "F", 206, 0.0, 13.5, 22.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Beef Stir-Fry", "F", 168, 2.6, 10.5, 16.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Mashed Potatoes", "F", 94, 17.0, 2.2, 1.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Fruit Salad", "F", 70, 18.0, 0.2, 0.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Taco", "F", 217, 17.4, 11.0, 12.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Veggie Burger", "F", 124, 14.8, 4.7, 5.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Caesar Wrap", "F", 218, 16.9, 13.1, 9.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Noodle Soup", "F", 38, 4.8, 0.7, 3.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Hamburger", "F", 250, 29.0, 10.0, 12.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Fajitas", "F", 159, 9.3, 6.1, 16.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Shrimp Scampi", "F", 181, 3.6, 8.2, 23.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Egg Fried Rice", "F", 218, 27.0, 9.0, 6.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Lasagna", "F", 132, 13.2, 5.2, 8.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Alfredo", "F", 199, 3.3, 7.7, 26.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Fried Shrimp", "F", 240, 19.0, 12.0, 14.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Eggplant Parmesan", "F", 143, 9.4, 9.5, 5.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Grilled Chicken Wrap", "F", 178, 24.1, 4.5, 10.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pancakes with Syrup", "F", 227, 31.3, 9.2, 5.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Steak Fajitas", "F", 198, 5.5, 6.7, 29.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Falafel", "F", 333, 36.3, 18.3, 13.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Tabbouleh", "F", 99, 12.8, 5.1, 2.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Shawarma (Chicken)", "F", 215, 4.3, 11.9, 21.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Moutabal (Baba Ganoush)", "F", 267, 8.5, 25.0, 4.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Kabsa (Chicken)", "F", 237, 35.8, 6.2, 10.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Manakeesh (Cheese)", "F", 322, 39.6, 13.1, 11.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Mujadara", "F", 202, 35.8, 3.7, 8.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Lamb Kofta", "F", 297, 2.5, 23.6, 20.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Baklava", "F", 429, 54.0, 22.5, 5.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Samosa (Vegetable)", "F", 252, 27.6, 14.3, 3.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Fattoush Salad", "F", 82, 12.1, 3.4, 2.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Shish Taouk", "F", 162, 3.5, 4.3, 26.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Makloubeh", "F", 153, 18.9, 5.9, 6.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Kunafa", "F", 320, 40.0, 16.0, 5.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Lentil Soup", "F", 111, 20.3, 0.6, 6.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Mansaf", "F", 443, 30.3, 24.2, 25.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Mandi", "F", 268, 22.8, 12.6, 16.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Stuffed Grape Leaves (Warak Enab)", "F", 162, 22.4, 7.3, 2.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Labneh", "F", 116, 3.6, 10.9, 1.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Parmesan", "F", 295, 10.3, 11.4, 37.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Beef Burrito", "F", 163, 20.4, 5.3, 8.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Tenders", "F", 319, 13.7, 17.8, 25.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Beef Tacos", "F", 226, 15.2, 12.5, 13.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Shrimp Fried Rice", "F", 207, 26.7, 6.9, 9.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Beef and Broccoli Stir-Fry", "F", 168, 9.9, 8.6, 14.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Quesadilla", "F", 247, 20.2, 11.6, 16.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Fish and Chips", "F", 273, 23.4, 15.5, 10.5);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Spaghetti Carbonara", "F", 286, 23.2, 15.6, 11.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Caesar Wrap", "F", 219, 15.5, 13.2, 12.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("BBQ Ribs", "F", 361, 10.5, 22.6, 27.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Turkey Club Sandwich", "F", 279, 24.6, 12.5, 17.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Enchiladas", "F", 207, 18.4, 8.2, 15.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Beef Stir-Fry with Vegetables", "F", 162, 7.8, 7.6, 15.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Salmon Teriyaki", "F", 222, 7.1, 13.6, 16.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Vegetable Curry", "F", 115, 11.7, 6.7, 2.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Beef Stroganoff", "F", 214, 6.6, 12.5, 18.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Tofu Stir-Fry", "F", 144, 8.0, 8.0, 12.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Chicken Shawarma", "F", 213, 17.8, 6.1, 20.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Mango Juice", "F", 60, 15.0, 0.0, 0.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Tahini Sauce", "F", 595, 5.0, 60.0, 15.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Laban", "F", 63, 4.3, 1.6, 7.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Kanafeh", "F", 321, 36.9, 17.7, 4.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Moroccan Mint Tea", "F", 49, 12.3, 0.1, 0.1);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Zaatar", "F", 395, 38.0, 25.0, 11.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Kunafa with Cheese", "F", 316, 43.6, 12.9, 6.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Rose Water", "F", 0, 0.0, 0.0, 0.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Basbousa", "F", 288, 39.8, 13.6, 3.6);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Sumac", "F", 305, 57.7, 4.9, 9.7);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Lemonade", "F", 29, 8.1, 0.1, 0.4);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Luqaimat", "F", 328, 49.6, 13.4, 4.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Cardamom", "F", 311, 68.0, 6.7, 10.8);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Karak Chai", "F", 84, 14.4, 2.5, 1.3);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Umm Ali", "F", 350, 26.0, 25.0, 5.0);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Pomegranate Juice", "F", 83, 18.7, 0.2, 1.2);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Harissa", "F", 84, 15.2, 2.1, 1.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Saffron", "F", 310, 65.0, 6.0, 11.9);
INSERT INTO diet_food (name, category, calories, carbs, fats, protein) VALUES ("Jallab", "F", 110, 27.0, 0.0, 0.0);
