# Generated by Django 4.1.7 on 2023-03-07 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_trainee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('F', 'Food'), ('B', 'Beverage'), ('S', 'Seasoning')], default='F', max_length=1)),
                ('calories', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('protein', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('instructions', models.TextField()),
                ('super_recipe', models.ManyToManyField(related_name='recipes', to='diet.recipe')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('time_eaten', models.DateTimeField(auto_now=True)),
                ('recipes', models.ManyToManyField(related_name='meals', to='diet.recipe')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.IntegerField()),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='diet.food')),
                ('meals', models.ManyToManyField(related_name='foodinstances', to='diet.meal')),
                ('recipes', models.ManyToManyField(related_name='foodinstances', to='diet.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='diet.food')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainee')),
            ],
            bases=('diet.food',),
        ),
    ]
