# Generated by Django 4.2.1 on 2023-05-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_remove_rating_user_rating_trainee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-timestamp']},
        ),
    ]
