# Generated by Django 4.1.7 on 2023-04-26 21:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('body_part', models.CharField(choices=[('CH', 'Chest'), ('BK', 'Back'), ('AR', 'Arms'), ('LG', 'Legs'), ('CR', 'Cardio'), ('SH', 'Shoulders'), ('AB', 'Abs')], default='CR', max_length=2)),
                ('calories_burned', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_repetitive', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='gym/images/exercises')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gym/images/workouts')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='core.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='PerformedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('time_performed', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_workouts', to='core.trainee')),
                ('workouts', models.ManyToManyField(related_name='performed_workouts', to='gym.workout')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_instances', to='gym.exercise')),
                ('performed_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_instances', to='gym.performedworkout')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_instances', to='gym.workout')),
            ],
            options={
                'verbose_name': 'Exercise Instance',
                'verbose_name_plural': 'Exercises Instance',
                'db_table': 'gym_exercise_instance',
            },
        ),
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.exercise')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to='core.trainee')),
            ],
            options={
                'verbose_name': 'Custom Exercise',
                'verbose_name_plural': 'Custom Exercises',
                'db_table': 'gym_custom_exercise',
            },
            bases=('gym.exercise',),
        ),
    ]
