# Generated by Django 4.1.7 on 2023-04-24 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(choices=[('CH', 'Chest'), ('BK', 'Back'), ('AR', 'Arms'), ('LG', 'Legs'), ('CR', 'Cardio'), ('SH', 'Shoulders'), ('AB', 'Abs')], default='CR', max_length=2),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
