# Generated by Django 4.2.1 on 2023-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_workout_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='rating_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
